spring.datasource.url=jdbc:h2:mem:maindb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

rule.datasource.url=jdbc:postgresql://localhost:5432/rule_db
rule.datasource.username=rule_user
rule.datasource.password=rule_password
rule.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:db/changelog/master.yaml
spring.jpa.hibernate.ddl-auto=none
