server.port=8080
spring.application.name=recommendations-mvp
spring.datasource.jdbc-url=jdbc:h2:mem:maindb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
rule.datasource.jdbc-url=jdbc:postgresql://localhost:5432/rule_db
rule.datasource.driver-class-name=org.postgresql.Driver
rule.datasource.username=postgres
rule.datasource.password=
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/master.yaml
logging.level.root=INFO
logging.level.com.starbank.recommendations=DEBUG
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate.SQL=DEBUG
